<?php
//file path constants
define("UPLOADS_DIR", dirname(dirname(__FILE__))."/upload");
define("DOMAIN_NAME", "http://rehabmypatient.com");

//image size constants
define("IMAGE_SIZE_SMALL", 65);
define("IMAGE_SIZE_LARGE", 230);

//HTTP method constants
define('HTTP_METHOD_GET', 'get');
define('HTTP_METHOD_POST', 'post');
define('HTTP_METHOD_PUT', 'put');
define('HTTP_METHOD_DELETE', 'delete');

//db constants
define('DB_HOST', 'localhost');
define('DB_NAME', 'rehabmyp_site');
define('DB_USER', 'rehabmyp');
define('DB_PASS', 'eHJis92UGjDq');

//service names constants
define('REST_SERVICE_LOGIN', 'login');
define('REST_SERVICE_EXERCISES', 'exercises');
define('REST_SERVICE_PATIENTS', 'patients');

//http response codes
define('HTTP_RESPONSE_CODE_CONTINUE',100);
define('HTTP_RESPONSE_CODE_SWITCHING_PROTOCOLS',101);
define('HTTP_RESPONSE_CODE_OK',200);
define('HTTP_RESPONSE_CODE_CREATED',201);
define('HTTP_RESPONSE_CODE_ACCEPTED',202);
define('HTTP_RESPONSE_CODE_NON_AUTHORITATIVE_INFORMATION',203);
define('HTTP_RESPONSE_CODE_NO_CONTENT',204);
define('HTTP_RESPONSE_CODE_RESET_CONTENT',205);
define('HTTP_RESPONSE_CODE_PARTIAL_CONTENT',206);
define('HTTP_RESPONSE_CODE_MULTIPLE_CHOICES',300);
define('HTTP_RESPONSE_CODE_MOVED_PERMANENTLY',301);
define('HTTP_RESPONSE_CODE_FOUND',302);
define('HTTP_RESPONSE_CODE_SEE_OTHER',303);
define('HTTP_RESPONSE_CODE_NOT_MODIFIED',304);
define('HTTP_RESPONSE_CODE_USE_PROXY',305);
define('HTTP_RESPONSE_CODE_(UNUSED)',306);
define('HTTP_RESPONSE_CODE_TEMPORARY_REDIRECT',307);
define('HTTP_RESPONSE_CODE_BAD_REQUEST',400);
define('HTTP_RESPONSE_CODE_UNAUTHORIZED',401);
define('HTTP_RESPONSE_CODE_PAYMENT_REQUIRED',402);
define('HTTP_RESPONSE_CODE_FORBIDDEN',403);
define('HTTP_RESPONSE_CODE_NOT_FOUND',404);
define('HTTP_RESPONSE_CODE_METHOD_NOT_ALLOWED',405);
define('HTTP_RESPONSE_CODE_NOT_ACCEPTABLE',406);
define('HTTP_RESPONSE_CODE_PROXY_AUTHENTICATION_REQUIRED',407);
define('HTTP_RESPONSE_CODE_REQUEST_TIMEOUT',408);
define('HTTP_RESPONSE_CODE_CONFLICT',409);
define('HTTP_RESPONSE_CODE_GONE',410);
define('HTTP_RESPONSE_CODE_LENGTH_REQUIRED',411);
define('HTTP_RESPONSE_CODE_PRECONDITION_FAILED',412);
define('HTTP_RESPONSE_CODE_REQUEST_ENTITY_TOO_LARGE',413);
define('HTTP_RESPONSE_CODE_REQUEST_URI_TOO_LONG',414);
define('HTTP_RESPONSE_CODE_UNSUPPORTED_MEDIA_TYPE',415);
define('HTTP_RESPONSE_CODE_REQUESTED_RANGE_NOT_SATISFIABLE',416);
define('HTTP_RESPONSE_CODE_EXPECTATION_FAILED',417);
define('HTTP_RESPONSE_CODE_INTERNAL_SERVER_ERROR',500);
define('HTTP_RESPONSE_CODE_NOT_IMPLEMENTED',501);
define('HTTP_RESPONSE_CODE_BAD_GATEWAY',502);
define('HTTP_RESPONSE_CODE_SERVICE_UNAVAILABLE',503);
define('HTTP_RESPONSE_CODE_GATEWAY_TIMEOUT',504);
define('HTTP_RESPONSE_CODE_HTTP_VERSION_NOT_SUPPORTED',505);


?>